#!/usr/bin/env sh

export HELPER="$HOME/.config/sketchybar/helper/helper"


source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh" # Loads all defined icons

ITEM_DIR="$HOME/.config/sketchybar/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins" # Directory where all the plugin scripts are stored

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
SPACE_CLICK_SCRIPT="aerospace workspace \$SID" # The script that is run for clicking on space components

PADDINGS=3 # All paddings use this value (icon, label, background)

POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11

SHADOW=on

# Setting up the general bar appearance and default values
sketchybar --bar     height=32                                         \
                     color=$BAR_COLOR                                  \
                     shadow=$SHADOW                                    \
                     position=top                                     \
                     sticky=on                                         \
                     padding_right=30                                  \
                     padding_left=0                                   \
                     corner_radius=9                                   \
                     y_offset=0                                       \
                     margin=0                                         \
                     blur_radius=20                                    \
                                                                       \
           --default updates=when_shown                                \
                     icon.font="$FONT:Bold:14.0"                       \
                     icon.color=$ICON_COLOR                            \
                     icon.padding_left=$PADDINGS                       \
                     icon.padding_right=$PADDINGS                      \
                     label.font="$FONT:Semibold:13.0"                  \
                     label.color=$LABEL_COLOR                          \
                     label.padding_left=$PADDINGS                      \
                     label.padding_right=$PADDINGS                     \
                     background.padding_right=$PADDINGS                \
                     background.padding_left=$PADDINGS                 \
                     popup.background.border_width=2                   \
                     popup.background.corner_radius=11                 \
                     popup.background.border_color=$POPUP_BORDER_COLOR \
                     popup.background.color=$POPUP_BACKGROUND_COLOR    \
                     popup.background.shadow.drawing=$SHADOW

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"

# Center
# source "$ITEM_DIR/spotify.sh"

# Right
sketchybar --add item clock right \
           --set clock update_freq=10 script="$PLUGIN_DIR/clock.sh" \
                    label.font="SF Pro:Bold:14.0" \
                    label.color=$LABEL_COLOR \
                    label.padding_left=10

sketchybar --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
                    icon.font="Hack Nerd Font:Bold:16.0" \
                    label.font="SF Pro:Semibold:14.0" \
                    icon.color=$ICON_COLOR \
                    label.color=$LABEL_COLOR \
                    icon.padding_left=6 \
                    label.padding_left=4 \
                    label.padding_right=10 \
           --subscribe battery system_woke power_source_change




############## FINALIZING THE SETUP ##############
sketchybar --update

echo "sketchybar configuation loaded.."
